// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoEH89mFDVqIaVU0WFjAjfd6rnBrtJ7Wk',
    appId: '1:896545342776:android:6148ded42b779afd1e2dcd',
    messagingSenderId: '896545342776',
    projectId: 'tractal-a60b4',
    databaseURL: 'https://tractal-a60b4-default-rtdb.firebaseio.com',
    storageBucket: 'tractal-a60b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGA95JJo-pXqVwdTAyy0FJ6QMnw2LvYMg',
    appId: '1:896545342776:ios:f2fb5b00833dfe2d1e2dcd',
    messagingSenderId: '896545342776',
    projectId: 'tractal-a60b4',
    databaseURL: 'https://tractal-a60b4-default-rtdb.firebaseio.com',
    storageBucket: 'tractal-a60b4.firebasestorage.app',
    androidClientId: '896545342776-ngfp9bntl9uh3vg16o7hd05ift6hdhlh.apps.googleusercontent.com',
    iosBundleId: 'com.tractal.game.tictactic',
  );
}
